---
version: 2.1

orbs:
  opam: argent-smith/opam@dev:second

x-job-defaults: &job_defaults
  executor:
    name: opam/opam_workbench
    opam_image_tag: debian-10-ocaml-4.09
  depext_pkgs: conf-m4

workflows:
  test:
    jobs:
      - opam/run_tests:
          <<: *job_defaults
      - opam/build_package:
          <<: *job_defaults
