---
version: 2.1

orbs:
  opam: argent-smith/opam@dev:second

workflows:
  test:
    jobs:
      - opam/run_tests:
          executor:
            name: opam/opam_workbench
            opam_image_tag: debian-10-ocaml-4.09
          depext_pkgs: conf-m4
      - opam/build_package:
          executor:
            name: opam/opam_workbench
            opam_image_tag: debian-10-ocaml-4.09
          depext_pkgs: conf-m4
######
