---
version: 2.1

orbs:
  opam: argent-smith/opam@1.0.1

executors:
  opam: opam/default

x-job-defaults: &job_defaults
  executor:
    name: opam
    image: ocaml/opam2
    tag: alpine-3.11-ocaml-4.09
  depext_pkgs: conf-m4

workflows:
  ci:
    jobs:
      - opam/run_tests:
          <<: *job_defaults
