# -*- dockerfile -*-
FROM opam-work
#FROM argentoff/ocaml-workbench:arm64v8-0.0.7
LABEL maintainer="Pavel Argentov (argentoff@gmail.com)"
USER dev
RUN mkdir -p /home/dev/project
VOLUME /home/dev/project
WORKDIR /home/dev/project
COPY --chown=dev . .
RUN opam update && \
    opam upgrade && \
    opam install -y utop && \
    opam clean
RUN opam install . --deps-only -t -y

ENTRYPOINT [ "opam", "config", "exec", "--" ]
CMD [ "bash" ]
